# Generated by Django 3.2 on 2022-04-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
